### ISSUE TITLE
3D case model without angled edged

### ISSUE THREAD

**Issue by exetico** [nic6911/ESP32-C3-P1-Interface#1]
Hi,

Thank you for sharing the design.

Would you be able to make a version of the casing, without the angled edges? I can't really find a good reason to use appx. the same amount on support, instead of just having the design with edged "to the ground" without angled corners.

Or share the Fusion file itself, it it's made in Fusion.

![image](https://github.com/user-attachments/assets/8948fb67-29c7-4682-a593-5a436318ea70)

![image](https://github.com/user-attachments/assets/0e475a70-673b-4b2c-b41b-bec6dbdee603)

That would be much appreciated.

**Comment by nic6911** [comment]
I made it like this to look a little more appealing - I printed it the opposite way of what you show here. Support would be internal in the structure to make the outer appearance nice. But I'll add the source file so that you can edit as you like.

**Comment by exetico** [comment]
Thank you! Much appreciated.

That's a great amount of work, in that file. 

I'll drop the top and bottom without chamfer below.

[Top and Bottom without chamfer.zip](https://github.com/user-attachments/files/18232621/Top.and.Bottom.without.chamfer.zip)
